// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	feline "github.com/wallacetm/go-dev-skills/model/feline"
)

// RoarService is an autogenerated mock type for the RoarService type
type RoarService struct {
	mock.Mock
}

// DoRoar provides a mock function with given fields: _a0
func (_m *RoarService) DoRoar(_a0 feline.Feline) {
	_m.Called(_a0)
}

// NewRoarService creates a new instance of RoarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoarService {
	mock := &RoarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
